### ISSUE TITLE
addstat.cgi: Beim Laden von Vorgaben wird die Seite leer neu geladen

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/LoxBerry-Plugin-Stats4Lox#19]
Wenn man Expertenmodus macht, dann eine Vorgabe wählt und "Laden", wird die Seite neu geladen und die Felder oben sind wieder leer. Die neue Vorgabe wird aber geladen.

Die Werte sollten erhalten bleiben. 
Evt. die Vorgaben bereits mit dem Laden des Formulars als JS-Variable/Array mitschicken, und beim "Laden" nur noch aus der Variable die Felder befüllen. 
Oder beim Laden die Daten per Ajax abholen und die Felder befüllen.

![image](https://user-images.githubusercontent.com/14220265/44494334-a5e8a980-a66b-11e8-81be-25d2b1a2c8af.png)

**Comment by mschlenstedt** [comment]
Machen wir mit dem neuen Template-System gleich mit. Ich schließe das hier.
