### ISSUE TITLE
grafana-rrd-server für x86 und x64 kompilieren

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/LoxBerry-Plugin-Stats4Lox#21]
Auf den entsprechenden VMs lt. https://www.loxwiki.eu/x/GwI_Ag

Binaries gehören im Plugin in /bin/grafana-rrd-server/x86 bzw. x64

**Comment by mschlenstedt** [comment]
Auslagern in separates Plugin.

**Comment by christianTF** [comment]
Kommt ins Grafana-Plugin
