### ISSUE TITLE
Import: Komische Werte für Min-Value in der Datenbank

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/LoxBerry-Plugin-Stats4Lox#27]
```
0001|300|Aktuell: Außentemperatur|Außentemperatursensor|1|\-70|70||Wetter|00ac8517-0961-11e1-99b9f25d750310ed|Â°C|Lox1wireAsensor
0002|300|Puffer Zone 1|Puffer Zone 1 (Sensor)|1|\-10|110|UG Heizraum|Heizraum-Steuerung|064c731f-08d7-11e1-a64ba068b1bd23cb|Â°C|Lox1wireAsensor
```
Backslash Minus 70
(oder ist das ein Escaping?)

0: DB-Name / Statistic ID
1: Step
2: Description
3: Loxone-Name to fetch
4: Miniserver
5: Min
6: Max
7: Place
8: Category
9: UID
10: Unit
11: Block

Außerdem ist die Einheit (10) wahrscheinlich falsch encoded.

**Comment by christianTF** [comment]
https://github.com/mschlenstedt/LoxBerry-Plugin-Stats4Lox/issues/31

Wahrscheinlich das gleiche XML::Simple UTF-8 Problem

**Comment by christianTF** [comment]
Kein XML-Problem, sondern ein Problem beim Commandline-Aufruf zum Erstellen der DB-Einträge aus Import.cgi

**Comment by mschlenstedt** [comment]
Noch aktuell?

**Comment by christianTF** [comment]
Wird sich zeigen ☝️
