### ISSUE TITLE
fetch.cgi wird mehrmals gestartet

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/LoxBerry-Plugin-Stats4Lox#36]
Teilweise scheint fetch.pl mehrmals gestartet zu werden, z. B. alle 15 Minuten mit --step 180, --step 300 und --step 900. Das gibt ein Chaos im Logfile.

Eventuell mit Lock verhindern oder (besser) alternativ bei --step 900 auch die Vielfachen gleich mit holen.

https://github.com/mschlenstedt/LoxBerry-Plugin-Stats4Lox/blob/442bb7993a2142c091a0afad7e431ecc80bb94e6/bin/fetch.pl#L91

Zudem übr eigenes Crontab starten (neu seit LB 1.0), damit nicht immer zu "kurmmen" Zeiten die Daten geholt werden.

**Comment by christianTF** [comment]
Jeder Fetcher erstellt sein eigenes Logfile mit seinem Log-Intervall. Durcheinander kommt da nichts.
Der Fetcher holt nur die Daten für seinen --step, d.h. mit der derzeitigen Implementierung müssen die Fetcher mit unterschiedlichen Steps auch mehrfach ("gleichzeitig") laufen, weil jeder holt nur seine Daten.

![image](https://user-images.githubusercontent.com/14220265/58884831-6ca49600-86e1-11e9-9468-8f40ae87e24c.png)

Der Fetcher funktioniert jetzt jedenfalls richtig, ich sehe keinen Änderungsbedarf.

**Comment by mschlenstedt** [comment]
Schau hier:

![image](https://user-images.githubusercontent.com/16830799/58885528-acb84880-86e2-11e9-9619-7d9c8d3b0f18.png)
[20190604_151002_461_Fetch.log](https://github.com/mschlenstedt/LoxBerry-Plugin-Stats4Lox/files/3252808/20190604_151002_461_Fetch.log)

**Comment by mschlenstedt** [comment]
Die Cronjobs werden zeitgleich gestartet. Das bedeutet, dass die Fetch-Jobs, die ein Vielfaches voneinander sind (z. B. 5 und 15 Minuten) zeitgleich gestartet werden. Keine Ahnung, warum der "Anhang" am Dateinamen (hier 461) auch bei beiden gleich ist, aber es scheint so zu sein, dass beide Fetch-Instanzen in das gleiche Log schreiben.

Siehe hier: https://github.com/mschlenstedt/Loxberry/blob/master/system/cron/cron.d/lbdefaults

**Comment by christianTF** [comment]
Die Zahl nach der Zeit sind die Millisekunden. Dass da zwei Jobs zur gleichen Millisekunde dran kommen, ist echtes Glück (oder Bug?).  Bei mir sind drei Logs der gleichen Minute immer ca. 100 ms versetzt.
Sie fetchen aber richtig. Können wir hinten anstellen, hier was zu tun.
