### ISSUE TITLE
fetch.cgi: Überflüssige Module entfernen

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/LoxBerry-Plugin-Stats4Lox#37]
https://github.com/mschlenstedt/LoxBerry-Plugin-Stats4Lox/blob/442bb7993a2142c091a0afad7e431ecc80bb94e6/bin/fetch.pl#L37

Welche Module werden wirklich gebraucht?

Eventuell überflüssig:
use Cwd 'abs_path';
use RRDs;
use POSIX qw(ceil);

**Comment by christianTF** [comment]
Kannst du leicht probieren, indem du sie auskommentierst.
Cwd abs_path ist sicher noch von a.d. (altes Templatesystem).
RRDs verwende ich jedenfalls zum Abfragen der RRD-Infos.
POSIX ceil ist kaufmännisches Runden, das ist im Fetcher drin.

**Comment by mschlenstedt** [comment]
Und wozu benötigst du die rrd Infos?

**Comment by christianTF** [comment]
Import: 
- flushcached
- Abfragen des letzten Updates, der Stepsize, des Countertypen, der Datasources
- Werte schreiben

RRD-Sink:
- Abfragen der Datasources, Countertypen

Letztes Update brauche ich, damit ich beim Import bereits importierte Daten skippe.
Stepsize benötige ich für die Interpolation
Countertypen benötige ich, weil manche Datentypen keine Float-Werte zulassen (->Runden)
Datasources brauche ich, weil der Fetcher (Loxone-Source und RRD-Sink) mit mehreren Datasources pro RRD umgehen kann, bzw. um generell zu den o.g. Detailinfos der Datasources zu kommen.
