### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/LoxBerry-Plugin-Stats4Lox#4]
@mschlenstedt und @Woersty als alte Perl-Haudegen, ich bräuchte Hilfe mit Fileupload in Perl!

Ich muss das LoxPlan-File uploaden lassen, der Code dazu ist in dieser Datei:
https://github.com/christianTF/LoxBerry-Plugin-Stats4Lox/blob/master/webfrontend/cgi/uploadconfig.cgi
Das verwendete HTML-Template ist hier:
https://github.com/christianTF/LoxBerry-Plugin-Stats4Lox/blob/master/templates/multi/loxplan_uploadform.html
Das Formular wird hier https://github.com/christianTF/LoxBerry-Plugin-Stats4Lox/blob/master/webfrontend/cgi/import.cgi#L210 eingebunden, die Form-Action ist das uploadconfig.cgi.

Wenn ich das mache, bekomme ich keinen Upload-Stream (my $upload_filehandle = $cgi->upload('loxplan') ist leer.)
Gebe ich das Fehlerhandling weg, erhalte ich ein 0-Byte-File.

Ich habe mich damit schon zwei Abende gespielt und es nun übersprungen (hab meine Datei einfach ins Dateisystem kopiert), damit ich weiterkomme.

Könntet ihr einen Blick darauf werfen, was ich hier falsch mache?
Mit der Perl-Variante eines Dateiuploads werde ich nicht richtig schlau (in PHP ist halt ein einziger Befehl, und das File liegt im Dateisystem...).

Vielen Dank!!
Christian

**Comment by mschlenstedt** [comment]
Bau ich Dir zusammen . Ich weiß gar nicht was ihr alle gegen Perl habt? ;-)

**Comment by mschlenstedt** [comment]
@christianTF Habe die Version bei mir ins Repository geladen: https://github.com/mschlenstedt/LoxBerry-Plugin-Stats4Lox/blob/master/webfrontend/cgi/uploadconfig.cgi

Du könntest auch noch verschiedene Dinge vorab testen/abfangen (Dateigröße, Dateiendung, etc.), siehe dazu webfrontend/cgi/system/upgrade.cgi ab Zeile 250
