### ISSUE TITLE
All (Verbrauchszähler, Raumregler usw.)

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/LoxBerry-Plugin-Stats4Lox#7]
http://192.168.0.78/dev/sps/io/Verbrauch%20Waschmaschine/all
http://192.168.0.78/dev/sps/io/Regler%20Partyraum/all

usw. :-)

**Comment by mschlenstedt** [comment]
Stehe irgendwie auf dem Schlauch - was möchtest Du mir denn sagen? ;-)

**Comment by christianTF** [comment]
Sven hat gesagt, man bekommt die Werte des Verbrauchszähler nicht heraus, da dachte ich, dass das eine Möglichkeit wäre, es auf diese Weise zu erfassen. :-)

**Comment by mschlenstedt** [comment]
Kapiert :-) 

Value gibt da nur den Status des Tr-Eingangs aus (0/1) - wozu man das benutzen soll weiß wohl nur Loxone alleine :-) Ich hatte mir geholfen, indem ich einfach einen Status-Baustein an AQ des Verbrauchszählers gehängt hatte und und diesen dann per Statistik über DS-Type COUNTER erfasse.

Haben denn alle Bausteine "all"? Dann könnte man die URL zum Pullen der Werte auch ändern. Kann das gerade nicht testen, schaue ich mir aber mit an.

Wenn Zählerstände per COUNTER erfasst werden gibt es übrigens dann gleich die Schwierigkeit mit der GRafikengine. RRD macht daraus immer sekundenbezogene Werte, also kWh/s zum Beispiel. Im Diagramm will man ja aber kWh/h oder kWh/d oder soetwas haben. Vermutlich wird man da dann noch irgendwelche Umrechnungsoptionen mit anbieten müssen - was es aber auch wieder recht kompliziert werden lässt... So richtig habe ich noch keine Idee, wie man das "smart" und "DAU-fähig" lösen kann.

**Comment by christianTF** [comment]
In meiner importierten Verbrauchszählerstatistik hab ich auch schon bemerkt, dass der aufsummiert. 
Da hatte ich dir dann geschrieben,, dass wir auch eine Baustein-Spalte in die databases.dat reinnehmen sollten.
Einerseits könnte ich dann beim Import pro Baustein gleich entscheiden, dass wir einen anderen DS-Type brauchen, und es tun sich solche Automatismen auch bei der Graphengine auf (z.b. "Wenn Verbrauchszähler, dann jenes Template, sonst ein anderes").
Die Einheit ebenso, damit man die in der Grafik anzeigen kann.

Ich habe beim Import das Problem mit mehreren Daten pro Baustein auch - hab ich nicht berücksichtigt, und jetzt müsste ich zwei oder mehr rrd's handhaben. Oder addstat legt mehrere DS in einem RRD an, dann musst du alles ändern und ich auch, weil ich vor dem Import gar nicht weiß, dass es mehrere Felder gibt, und die Graphengine müsste das auch wieder wissen. (Option 1 ist leichter zu implementieren, das bleibt bei mir).

Das /all geht nach meinen Tests bei allen Bausteinen. Da habe ich bei meinen Imports wieder ein Problem, weil ich diese Daten gar nicht bekomme, und ich auch keine Zuordnung des XML-Datensatzes zum Namen in /all habe. Alles nicht trivial...

Wenn du /all nachimplementierst, musst du jedenfalls noch eine Spalte für den Ausgang hineinnehmen.

Was haben wir da nur angefangen... ;-)

**Comment by mschlenstedt** [comment]
Hab mich auch schon gefragt was das für einen Rattenschwanz nach sich zieht :-)

Ich verlagere die Duskussion mal zurück ins Forum - das ist etwas komfortabler...
